dist: xenial

language: python
python:
  - '3.7'

script: make build

deploy:
  provider: pypi
  user: lifeofguenter
  password:
    secure: BEKX/glqfqQoap1rxqd5+P989NYzn+OhthtFhnxXADg8QRXmnHZCXjKkBIFFki7Hd2wNhA23C1YUoYQRNNAFdxQhul8nb5aidNdXrU3nKx6uh6DRpGGLSGrCF+NJvGVC3uwVaJvUWeOvSrOgZBF3g0FKjdFYF7+P4q4yBNpprTCg1EMs+4FDBiVHud4HsloXKga0zYdugX2AnySKAlhjvBxdKzSrVtXd7Pz/uAjCO1M5Ek207etk5Xfuz9mO7kkf1OMlL5SvcM8ehz3JXgrWOtDxJMUE/bLs6vVoMcRjSQhPe+DoDwSRNKzn6qabBchIul3m40R0Fgeme0lL34BkAiyY1a+aEU1edKmBaGEj6JsRKpKOQ35CA1bvvV62elKddK4dUUUnGCMk86782Gtnu86lXDKdURZpPwbzN7U2srhLSQP4G+0IuckG0s2pLGO/u+ujo3GAUTgWS/Y5LT0K+r6ELaZRgul9vmSyicSn8I8BxnBtdwt7zp6CaZzJOQZJXOgzFuyR9fbJ5B60m0iT/SLB0VZVmItg0JO4wUPGR/KesIf8SHCMeelyWiJDw6eKqJPZpD/IAffbOx61CWGx6iLICIbLsokK+EhUP33WgbYKfWAIBxb7D3VY0oiXca+JAMEK6ovRSreo0j0CXIwIlV4JDlkZZfwkdDw537Bkzic=
  on:
    tags: true
